config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#index"
  resources :items, only: [:index, :show, :create] do
    resources :order_items, only: [:create, :destroy]
    collection do
      post 'create_from_scan'
    end
    member do
      get :find_item
    end
  end

  resources :carts, only: [:index, :show]

  patch 'carts/:id', to: 'carts#send_order_to_merchant'

  get 'dashboard', to: 'users#show', as: 'dashboard'

  post 'items/:id', to: 'my_stocks#duplicate_item', as: 'duplicate_item'

  get 'my_stock', to: 'my_stocks#show', as: 'my_stock'

  get 'my_stock/items/new', to: 'my_stocks#add_item', as: 'add_item_to_stock'
  post 'my_stock/items', to: 'my_stocks#create_item'



  get 'my_stock/items/:id', to: 'my_stocks#show_item', as: 'show_item_in_stock'

  get 'my_stock/items/:id/edit', to: 'my_stocks#edit_item', as: 'edit_item_in_stock'
  patch 'my_stock/items/:id', to:'my_stocks#update_item'

  delete 'items/:id', to: 'my_stocks#destroy_item', as: 'destroy_item_in_stock'

  resources :orders, only: [:index, :show]
  resources :orders do
    member do
      patch :validate_order
      patch :refuse_order
      patch :deliver_order
    end
  end




  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/my_stocks_controller.rb
require 'open-uri'


class MyStocksController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:create_item, :duplicate_item]

  def show
    @items = current_user.companies.first.items.in_stock
    @unique_items = remove_duplicates(@items)
  end

  def show_item
    @item = current_stock.find(params[:id])
  end

  def add_item
    @user = current_user
    @company = Company.find_by(user_id: @user.id)
    @item = @company.items.new
  end

  def create_item
    @user = current_user
    @company = Company.find_by(user_id: @user.id)
    # Assuming you are expecting 'data' in params sent from the frontend
    data = params[:data]

    item = Item.new(
      reference: data['styleId'],
      brand: data['brand'],
      model: data['name'],
      color: data['colorway'],
      price: 10,
      company: current_user.companies.first,
      size: 40,
      released_on: Date.new(data['year'].to_i)
    )
    unless data['media']['imageUrl'].nil?
      file = URI.open(data['media']['imageUrl'])
      item.photo.attach(io: file, filename: 'shoe.png' , content_type: 'image/png')
    end
    item.save!
  end

  def edit_item
    @item = current_stock.find(params[:id])
  end

  def update_item
    @item = current_stock.find(params[:id])
    @item.update(item_params)
    redirect_to show_item_path(@item)
  end

  def destroy_item
    @item = current_stock.find(params[:id])
    items = @item.same_in_stock.all
    @item.destroy
    if items.empty?
      flash[:alert] = "Il n'y en a plus"
    else
      flash[:notice] = "Produit supprimé"
    end
  end

  def duplicate_item
    @item = current_stock.find(params[:id])
    @new_item = @item.dup
    if @item.photo.attached?
      @new_item.photo.attach(@item.photo.blob)
    end
    @new_item.save
  end

  private

  def remove_duplicates(items)

    unique_items = {}

    items.each do |item|
      key = [item.reference, item.brand, item.model, item.color, item.price, item.size]

      if unique_items[key]
        unique_items[key][:count] += 1
      else
        unique_items[key] = { item: item, count: 1 }
      end
    end

    sorted_unique_items = unique_items.values.sort_by { |entry| -entry[:count] }

    sorted_unique_items.map { |entry| entry[:item] }
  end

  def is_duplicate?(item1, item2)
    item1.reference == item2.reference &&
    item1.brand == item2.brand &&
    item1.model == item2.model &&
    item1.color == item2.color &&
    item1.price == item2.price
  end

  def item_params
    params.require(:item).permit(:reference, :brand, :model, :color, :price, :size, :company_id)
  end
end

app/helpers/my_stocks_helper.rb
module MyStocksHelper
end

app/views/my_stocks/_item_overlay.html.erb
<div class="overlay-container" data-action="click->overlay#remove_overlay" id="item_<%= item.id%>">
  <div class="overlay container" data-action="click->overlay#prevent">
    <div class="cross container" data-action="click->overlay#remove_overlay">
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
        <path stroke-linecap="round" stroke-linejoin="round" d="M6 18 18 6M6 6l12 12" />
      </svg>
    </div>
    <div class="title container">
      <h4>Details du produit</h4>
    </div>
    <div class="infos">
      <div class="overlay-image container">
        <% if !item.photo.key.nil? %>
          <%= cl_image_tag item.photo.key, crop: :fill, alt: "shoe", class: "product-image-items"%>
        <% else %>
          <div class="product-image-placeholder"></div>
        <% end %>
      </div>
      <div class="main-infos">
        <p>
          <strong><%= item.brand %></strong><br>
          <%= item.model %>
        </p>
        <p>
          Taille <%= item.size %><br><br>
          <strong><%= item.price %>€</strong>
        </p>
      </div>
    </div>
      <div class="complementary-infos container">
      <p>couleur(s) : <%= item.color %></p>
      <p>référence : <%= item.reference %></p>
      <div class="quantity-selector">
      <%= button_to "-", destroy_item_in_stock_path(item), method: :delete, class: "quantity-btn minus" %>
          <span class="quantity-value">Quantité : <%= item.same_in_stock.count %></span>
      <%= button_to "+", duplicate_item_path(item), method: :post, class: "quantity-btn minus" %>
    </div>
      </div>
  </div>
</div>

app/views/my_stocks/_new_item_overlay.html.erb
<div class="overlay-container" data-controller="overlay"  data-barcode-target="overlay">
  <%= form_with model: Item.new, class: "overlay container" do |f| %>
    <div class="cross container" data-action="click->overlay#remove_overlay">
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
        <path stroke-linecap="round" stroke-linejoin="round" d="M6 18 18 6M6 6l12 12" />
      </svg>
    </div>
    <div class="title container">
      <h4>Détails du produit</h4>
    </div>
    <div class="infos">
      <div class="overlay-image container">
        <%= f.hidden_field :photo, data: { barcode_target: "photoInput" } %>
        <div id="staticContent" data-barcode-target="photo"></div>
      </div>
      <div class="item-main-infos">
        <%= f.hidden_field :brand, data: { barcode_target: "brandInput" } %>
        <div id="staticContent" data-barcode-target="brand"></div>
        <%= f.hidden_field :model, data: { barcode_target: "modelInput" } %>
        <div id="staticContent" data-barcode-target="model"></div>
        <div class="info-again">
          <div class="size">
            Taille
            <br>
            <%= f.text_field :size, value: 40, class: "little-input" %>
          </div>
          <div class="price">
            Prix (€)
            <br>
            <%= f.text_field :price, value: 40, class: "little-input" %>
          </div>
        </div>
      </div>
    </div>
    <div class="complementary-infos container">
      <div class="reference">
        <%= f.hidden_field :reference, data: { barcode_target: "referenceInput" }, id: "hiddenReference" %>
        <div id="staticContent" data-barcode-target="reference"></div>
      </div>
          <div class="barcode">
        <%= f.hidden_field :barcode,  data: { barcode_target: "barcodeInput" }, id: "hiddenbarcode" %>
        <div id="staticContent" data-barcode-target="barcode"></div>
      </div>
    <div class="color">
        Couleur(s)
        <br>
        <%= f.text_field :color, value: "Noir", class: "big-input" %>
    </div>
    <div class="quantity-selector-new">
      <div class="quantity-value">
        Quantité :
        <br>
        <input name="quantity" type="text" value="5" class="big-input">
      </div>
    </div>
    </div>
    <%= f.submit "Ajouter au stock", class:"carts-view-details-button add-stock-btn" %>
  <% end %>
</div>

app/views/my_stocks/add_item.html.erb
<div data-controller="barcode">
  <div class="overlay-back"></div>
  <div class="add_item container">
    <h3>Scanner le code barre</h3>

    <div class="contain">
      <div id="scan-image">
        <video class="video" id="barcode-scanner" autoplay playsinline></video>
      </div>
      <input type="text" id="barcode_input" hidden />
    </div>

    <div class="separator">ou</div>

    <div class="manual-input">
        <h3>Saisir manuellement</h3>
    </div>

    <div class="search-bar-container" data-controller="reference-manual">
      <input type="text" placeholder="Saisissez la référence ici" data-reference-manual-target="input">
      <button class="validate-scan" data-action="click->reference-manual#fetchSneaker">Valider</button>
    </div>
  </div>
  <%= render("my_stocks/new_item_overlay") %>

  <%= render("users/footer_sales") %>
</div>

app/views/my_stocks/copy.html.erb
<div id="scan-image" data-controller="barcode">
        <video class="video" id="barcode-scanner" autoplay></video>
        <input type="text" id="barcode_input" hidden />
      </div>

app/views/my_stocks/edit_item.html.erb
<h1>I edit my item</h1>

app/views/my_stocks/show.html.erb
<div class="overlay-back"></div>
<div class="my_stocks container">
  <div class="content-wrapper">
    <h2 class="title-stock">Inventaire</h2>
      <div class="search-container">
        <input type="text" placeholder="Rechercher un modèle..." class="search-input" onkeyup="filterModels()">
        <button class="filter-button" onclick="toggleFilterOverlay()">
          Filtrer
        </button>
      </div>
      <p class="item-en-stock-count"><strong><%= @items.count %></strong> produits en stock</p>
      <ul class="inventory-list" data-controller="overlay">
      <% @unique_items.each do |item| %>
        <li class="inventory-item" data-action="click->overlay#deploy_overlay" data-id="<%= item.id %>">
          <div class="product-info">
              <div class="product-image">
                <% if !item.photo.key.nil?%>
                  <%= cl_image_tag item.photo.key, crop: :fill, transformation: [
                    { effect: "make_transparent", color: "white", tolerance: 100 },
                    { effect: "trim", color: "white", tolerance: 0 }
                      ], alt: "shoe", class: "stock-item" %>
                  <% end %>
              </div>
              <h2 class="product-name-stock"><%= item.brand %> <%= item.model %></h2>
            </div>
            <div class="product-controls">
              <span class="total-text">| Quantité: <span id="product-quantity-1"><%= item.same_in_stock.count %></span> <br>
              | Taille: <%= item.size %></span>
              <%# <button class="quantity-button" onclick="decreaseQuantity(1)">-</button> %>
              <%# <button class="quantity-button" onclick="increaseQuantity(1)">+</button> %>
          </div>
        </li>
        <%= render "my_stocks/item_overlay", item: item %>
        <% end %>
      </ul>
    <!-- Répétez pour d'autres produits -->

  <%# <%= link_to add_item_to_stock_path do   %>
    <%# <button type="submit" id="round-button"><i class="fa-solid fa-plus"></i></button>
  <% end %>


  <div id="filter-overlay" class="filter-overlay" style="display: none;">
    <div class="filter-content">
      <h2>Filtrer les résultats</h2>
      <label for="brand">Marque</label>
      <input type="text" id="brand" placeholder="Ex : Nike">

      <label for="color">Couleur</label>
      <input type="text" id="color" placeholder="Ex : Rouge">

      <label for="size">Taille</label>
      <input type="text" id="size" placeholder="Ex : 40">

      <label for="reference">Numéro de référence</label>
      <input type="text" id="reference" placeholder="Ex : 123456">

      <label for="price">Prix maximum</label>
      <input type="number" id="price" placeholder="Ex : 100" min="0">

      <button class="apply-button" onclick="applyFilters()">Appliquer les filtres</button>
      <button class="close-button" onclick="toggleFilterOverlay()">Fermer</button>
    </div>
  </div>

  <%= render("users/footer_sales") %>
  </div>
</div>

<%# ========================================================================================= %>

<script>
  function filterModels() {
    const input = document.querySelector('.search-input');
    const filter = input.value.toLowerCase();
    const items = document.querySelectorAll('.inventory-item');

    items.forEach(item => {
      const model = item.querySelector('.product-name-stock').textContent.toLowerCase();
      if (model.includes(filter)) {
        item.style.display = '';
      } else {
        item.style.display = 'none';
      }
    });
  }
</script>

<script>
  function toggleFilterOverlay() {
    const overlay = document.getElementById('filter-overlay');
    overlay.style.display = (overlay.style.display === 'block') ? 'none' : 'block';
  }

  function decreaseQuantity(productId) {
    const quantityElement = document.getElementById('product-quantity-' + productId);
    let quantity = parseInt(quantityElement.textContent);
    if (quantity > 0) {
      quantity -= 1;
      quantityElement.textContent = quantity;
    }
  }

  function increaseQuantity(productId) {
    const quantityElement = document.getElementById('product-quantity-' + productId);
    let quantity = parseInt(quantityElement.textContent);
    quantity += 1;
    quantityElement.textContent = quantity;
  }
</script>

app/views/my_stocks/show_item.html.erb
<h1>I can see details of the product in my stock </h1>

<%= @item.price %>
<%= @item.same_in_stock.count %>

<%= form_with model: @item, method: :post do |f| %>
  <%= f.label "add" %>
  <%= f.submit %>
<% end %>

<%= form_with model: @item, method: :delete do |f| %>
  <%= f.label "delete" %>
  <%= f.submit %>
<% end %>