config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#index"
  resources :items, only: [:index, :show, :create] do
    resources :order_items, only: [:create, :destroy]
    collection do
      post 'create_from_scan'
    end
    member do
      get :find_item
    end
  end

  resources :carts, only: [:index, :show]

  patch 'carts/:id', to: 'carts#send_order_to_merchant'

  get 'dashboard', to: 'users#show', as: 'dashboard'

  post 'items/:id', to: 'my_stocks#duplicate_item', as: 'duplicate_item'

  get 'my_stock', to: 'my_stocks#show', as: 'my_stock'

  get 'my_stock/items/new', to: 'my_stocks#add_item', as: 'add_item_to_stock'
  post 'my_stock/items', to: 'my_stocks#create_item'



  get 'my_stock/items/:id', to: 'my_stocks#show_item', as: 'show_item_in_stock'

  get 'my_stock/items/:id/edit', to: 'my_stocks#edit_item', as: 'edit_item_in_stock'
  patch 'my_stock/items/:id', to:'my_stocks#update_item'

  delete 'items/:id', to: 'my_stocks#destroy_item', as: 'destroy_item_in_stock'

  resources :orders, only: [:index, :show]
  resources :orders do
    member do
      patch :validate_order
      patch :refuse_order
      patch :deliver_order
    end
  end




  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :cart
  belongs_to :company
  has_many :order_items
  has_many :items, through: :order_items
  scope :not_sent, -> {where.not(status: nil)}

  def same_item(item)
    items.where(
      reference:item.reference,
      brand:item.brand,
      model:item.model,
      color:item.color,
      price:item.price,
      size:item.size
    )
  end

  def total_price
    items.sum(:price)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def index
    # le commercant consulte toutes ses commandes
    @user = current_user
    @orders = @user.companies.first.orders
  end

  def show
    # le commercant peut consulter une commande en particulier
    @user = current_user
    @order = @user.companies.first.orders.find(params[:id])
  end

  def validate_order
    # le commercant peut accepter une commande émise par le client.
    # status est à nil par défault.
    # Quand le commercant accepte,status devient 'validée'
    @user = current_user
    @order = @user.companies.first.orders.find(params[:id])
    @order.update(status: 'Validée')
    @client_id = @order.cart.user.id
    cart = Cart.where(user_id: @client_id)
    cart.update(validated_on: Date.today)
    redirect_to orders_path
  end

  def refuse_order
    # le commercant peut refuser une commande émise par le client.
    # status est à nil par défault.
    # Quand le commercant accepte,status devient 'Refusée'
    @user = current_user
    @order = @user.companies.first.orders.find(params[:id])
    @order.update(status: 'Refusée')
    redirect_to orders_path
  end

  def deliver_order
    @user = current_user
    @order = @user.companies.first.orders.find(params[:id])
    @order.update(status: 'Effectuée')
    redirect_to orders_path
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/index.html.erb
<div class="orders-page-container">
  <header class="orders-header">
    <h1 class="orders-title">Toutes les commandes</h1>
  </header>

  <!-- New Orders Section -->
  <section class="orders-section">
    <h2 class="orders-section-title">Nouvelles commandes</h2>
    <% if @orders.where(status: "En attente").empty?  %>
      <p class="no-orders-message">Pas de nouvelles commandes pour le moment...</p>
    <% else  %>
      <% @orders.where(status: "En attente").each do |o|  %>
        <div class="order-card" data-controller="order-details" data-action="click->order-details#toggleDetails">
          <!-- Order Card Content -->
          <div class="order-card-content">
            <div class="order-info">
              <div class="avatar-circle">
                <span class="initials"><%= o.cart.user.initials %></span>
              </div>
              <div class="order-details">
                <div class="order-product-name"><%= "#{o.cart.user.last_name} #{o.cart.user.first_name}" %></div>
                <div class="order-date"><%= "#{o.ordered_on}" %></div>
              </div>
            </div>
            <div class="order-actions">
              <div class="order-buttons-wrapper">
                <%= button_to "Accepter", validate_order_order_path(o), data: {turbo_method: :patch}, method: :patch, class: "order-accept-button" %>
                <%= button_to "Refuser", refuse_order_order_path(o), data: {turbo_method: :patch}, method: :patch, class: "order-decline-button" %>
              </div>
            </div>
          </div>
          <!-- Order Hidden Details -->
          <div class="order-hidden-details" data-order-details-target="details" style="display: none;">
            <% grouped_items = o.items.group_by { |item| [item.model, item.size, item.price] } %>
            <% grouped_items.each do |group, items| %>
              <div class="info-order">
                <p>
                  Modèle : <%= items.first.brand %> <%= items.first.model %><br>
                  Taille : <%= items.first.size %><br>
                  Quantité : <%= items.size %><br>
                  Prix unitaire : <%= items.first.price %>€
                </p>
              </div>
            <% end %>
            <div class="total">
              <p style="margin-bottom: -10px;">Total: <%= o.total_price %>€</p>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </section>

  <!-- Ready for Pickup Orders Section -->
  <section class="orders-section">
    <h2 class="orders-section-title">Commandes prêtes pour le retrait</h2>
    <% if @orders.where(status: "Validée").empty? %>
      <p class="no-orders-message">Pas de commandes en cours pour le moment...</p>
    <% else %>
      <% @orders.where(status: "Validée").each do |o|  %>
        <div class="order-card" data-controller="order-details" data-action="click->order-details#toggleDetails">
          <div class="pouff">
            <p>Expire dans 3 jours</p>
            <%= button_to "Récupérée ?", deliver_order_order_path(o), data: {turbo_method: :patch}, method: :patch, class: "btn-orders" %>
          </div>
          <div class="order-card-content">
            <div class="order-info">
              <div class="avatar-circle">
                <span class="initials"><%= o.cart.user.initials %></span>
              </div>
              <div class="order-details">
                <div class="order-product-name"><%= "#{o.cart.user.last_name} #{o.cart.user.first_name}" %></div>
                <div class="order-date"><%= "#{o.ordered_on}" %></div>
              </div>
            </div>
            <div class="all-buttons">
              <button id="btn-detail" class="order-view-details-button">Voir le détail</button >
            </div>
          </div>
          <!-- Order Hidden Details -->
          <div class="order-hidden-details" data-order-details-target="details" style="display: none;">
            <% grouped_items = o.items.group_by { |item| [item.model, item.size, item.price] } %>
            <% grouped_items.each do |group, items| %>
              <div class="info-order">
                <p>
                  Modèle : <%= items.first.brand %> <%= items.first.model %><br>
                  Taille : <%= items.first.size %><br>
                  Quantité : <%= items.size %><br>
                  Prix unitaire : <%= items.first.price %>€
                </p>
              </div>
            <% end %>
            <div class="total">
              <p style="margin-bottom: -10px;">Total: <%= o.total_price %>€</p>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </section>

  <!-- Previous Orders Section -->
  <section class="orders-section">
    <h2 class="orders-section-title">Commandes précédentes</h2>
    <% if @orders.where(status: "Effectuée").empty? %>
      <p class="no-orders-message">Pas de commandes précédentes pour le moment...</p>
    <% else %>
      <% @orders.where(status: "Effectuée").each do |o| %>
        <div class="order-card" data-controller="order-details" data-action="click->order-details#toggleDetails">
          <div class="order-card-content">
            <div class="order-info">
              <div class="avatar-circle">
                <span class="initials"><%= o.cart.user.initials %></span>
              </div>
              <div class="order-details">
                <div class="order-product-name"><%= "#{o.cart.user.last_name} #{o.cart.user.first_name}" %></div>
                <div class="order-date"><%= "#{o.ordered_on}" %></div>
              </div>
            </div>
            <div class="order-actions">
              <button id="btn-detail-finished" class="order-view-details-button">Voir le détail</button>
            </div>
          </div>
          <!-- Order Hidden Details -->
          <div class="order-hidden-details" data-order-details-target="details" style="display: none;">
            <% grouped_items = o.items.group_by { |item| [item.model, item.size, item.price] } %>
            <% grouped_items.each do |group, items| %>
              <div class="info-order">
                <p>
                  Modèle : <%= items.first.brand %> <%= items.first.model %><br>
                  Taille : <%= items.first.size %><br>
                  Quantité : <%= items.size %><br>
                  Prix unitaire : <%= items.first.price %>€
                </p>
              </div>
            <% end %>
            <div class="total">
              <p style="margin-bottom: -10px;">Total: <%= o.total_price %>€</p>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </section>
</div>

<%= render("users/footer_sales") %>

app/views/orders/show.html.erb
<h1>Je peux acceder au detail d'une commande</h1>
<p>en appuyant sur ce bouton le commercant valide la commande qu'il recoit</p>
  <%= form_with(model: @order, method: :patch) do |f| %>
  <%= f.label "Je valide la commande reçue" %>
  <%= f.submit %>
<% end %>