config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#index"
  resources :items, only: [:index, :show, :create] do
    resources :order_items, only: [:create, :destroy]
    collection do
      post 'create_from_scan'
    end
    member do
      get :find_item
    end
  end

  resources :carts, only: [:index, :show]

  patch 'carts/:id', to: 'carts#send_order_to_merchant'

  get 'dashboard', to: 'users#show', as: 'dashboard'

  post 'items/:id', to: 'my_stocks#duplicate_item', as: 'duplicate_item'

  get 'my_stock', to: 'my_stocks#show', as: 'my_stock'

  get 'my_stock/items/new', to: 'my_stocks#add_item', as: 'add_item_to_stock'
  post 'my_stock/items', to: 'my_stocks#create_item'



  get 'my_stock/items/:id', to: 'my_stocks#show_item', as: 'show_item_in_stock'

  get 'my_stock/items/:id/edit', to: 'my_stocks#edit_item', as: 'edit_item_in_stock'
  patch 'my_stock/items/:id', to:'my_stocks#update_item'

  delete 'items/:id', to: 'my_stocks#destroy_item', as: 'destroy_item_in_stock'

  resources :orders, only: [:index, :show]
  resources :orders do
    member do
      patch :validate_order
      patch :refuse_order
      patch :deliver_order
    end
  end




  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/pages/_footer.html.erb
<div class="footer-container-sales px-2" data-controller="footer">
  <div class="footer-icon-item" data-footer-target="item" data-action="click->footer#select">
    <%= link_to root_path do %>
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
      <path stroke-linecap="round" stroke-linejoin="round" d="m2.25 12 8.954-8.955c.44-.439 1.152-.439 1.591 0L21.75 12M4.5 9.75v10.125c0 .621.504 1.125 1.125 1.125H9.75v-4.875c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125V21h4.125c.621 0 1.125-.504 1.125-1.125V9.75M8.25 21h8.25" />
    </svg>
    <span>Accueil</span>
    <% end %>
  </div>

  <div class="footer-icon-item" data-footer-target="item" data-action="click->footer#select">
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
      <path stroke-linecap="round" stroke-linejoin="round" d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12Z" />
    </svg>
    <span>Favoris</span>
  </div>

  <div class="footer-icon-item" data-footer-target="item" data-action="click->footer#select">
  <%= link_to carts_path do %>
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
      <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 10.5V6a3.75 3.75 0 1 0-7.5 0v4.5m11.356-1.993 1.263 12c.07.665-.45 1.243-1.119 1.243H4.25a1.125 1.125 0 0 1-1.12-1.243l1.264-12A1.125 1.125 0 0 1 5.513 7.5h12.974c.576 0 1.059.435 1.119 1.007ZM8.625 10.5a.375.375 0 1 1-.75 0 .375.375 0 0 1 .75 0Zm7.5 0a.375.375 0 1 1-.75 0 .375.375 0 0 1 .75 0Z" />
    </svg>
    <span>Achats</span>
    <% end %>
  </div>

  <div class="footer-icon-item" data-footer-target="item" data-action="click->footer#select">
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
      <path stroke-linecap="round" stroke-linejoin="round" d="M14.857 17.082a23.848 23.848 0 0 0 5.454-1.31A8.967 8.967 0 0 1 18 9.75V9A6 6 0 0 0 6 9v.75a8.967 8.967 0 0 1-2.312 6.022c1.733.64 3.56 1.085 5.455 1.31m5.714 0a24.255 24.255 0 0 1-5.714 0m5.714 0a3 3 0 1 1-5.714 0M3.124 7.5A8.969 8.969 0 0 1 5.292 3m13.416 0a8.969 8.969 0 0 1 2.168 4.5" />
    </svg>
    <span>Notif.</span>
  </div>

  <div class="footer-icon-item" data-footer-target="item" data-action="click->footer#select">
  <% if !@user.nil? %>
      <!-- User is connected, just show the icon -->
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
        <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 6a3.75 3.75 0 1 1-7.5 0 3.75 3.75 0 0 1 7.5 0ZM4.501 20.118a7.5 7.5 0 0 1 14.998 0A17.933 17.933 0 0 1 12 21.75c-2.676 0-5.216-.584-7.499-1.632Z" />
      </svg>
      <span>Compte</span>
    <% else %>
      <!-- User is not connected, show the icon wrapped in a link -->
      <%= link_to new_user_session_path do %>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
          <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 6a3.75 3.75 0 1 1-7.5 0 3.75 3.75 0 0 1 7.5 0ZM4.501 20.118a7.5 7.5 0 0 1 14.998 0A17.933 17.933 0 0 1 12 21.75c-2.676 0-5.216-.584-7.499-1.632Z" />
        </svg>
        <span>Compte</span>
      <% end %>
    <% end %>
  </div>
</div>

app/views/pages/_form_with.html.erb
<%= form_with(url: items_path, method: :get, local: true, class: "d-flex")do %>
  <%= text_field_tag :query,
        params[:query],
        class: "search-model",
        placeholder: "Nike Airmax rouge"
    %>
  <div data-controller="localisation-autocomplete" data-localisation-autocomplete-api-key-value="pk.eyJ1Ijoia2V2cm82OSIsImEiOiJjbHphYXF6NXQwYzZhMmlzOGdtZDBldGxyIn0.zBm8EAuLoRwo_Mz3pZmLPw" class="mb-3 string required offer_localisation">
    <input class="form-control string required d-none" data-localisation-autocomplete-target="localisation" type="text" name="offer[localisation]" id="offer_localisation">
    <div class="mapboxgl-ctrl-geocoder mapboxgl-ctrl">
      <svg class="mapboxgl-ctrl-geocoder--icon mapboxgl-ctrl-geocoder--icon-search" viewBox="0 0 18 18" xml:space="preserve" width="18" height="18">
        <path d="M7.4 2.5c-2.7 0-4.9 2.2-4.9 4.9s2.2 4.9 4.9 4.9c1 0 1.8-.2 2.5-.8l3.7 3.7c.2.2.4.3.8.3.7 0 1.1-.4 1.1-1.1 0-.3-.1-.5-.3-.8L11.4 10c.4-.8.8-1.6.8-2.5.1-2.8-2.1-5-4.8-5zm0 1.6c1.8 0 3.2 1.4 3.2 3.2s-1.4 3.2-3.2 3.2-3.3-1.3-3.3-3.1 1.4-3.3 3.3-3.3z"></path>
      </svg>
      <input type="text" class="mapboxgl-ctrl-geocoder--input" placeholder="Chercher" aria-label="Chercher">
      <div class="suggestions-wrapper"><ul class="suggestions" style="display: none;">
        <div class="mapboxgl-ctrl-geocoder--powered-by" style="display: block;">
        <a href="https://www.mapbox.com/search-service" target="_blank">Powered by Mapbox</a></div>
        </ul></div><div class="mapboxgl-ctrl-geocoder--pin-right">
        <svg class="mapboxgl-ctrl-geocoder--icon mapboxgl-ctrl-geocoder--icon-loading" viewBox="0 0 18 18" xml:space="preserve" width="18" height="18" style="display: none;">
        <path fill="#333" d="M4.4 4.4l.8.8c2.1-2.1 5.5-2.1 7.6 0l.8-.8c-2.5-2.5-6.7-2.5-9.2 0z"></path>
        <path opacity=".1" d="M12.8 12.9c-2.1 2.1-5.5 2.1-7.6 0-2.1-2.1-2.1-5.5 0-7.7l-.8-.8c-2.5 2.5-2.5 6.7 0 9.2s6.6 2.5 9.2 0 2.5-6.6 0-9.2l-.8.8c2.2 2.1 2.2 5.6 0 7.7z"></path></svg>
        </div>
        </div>
        </div>

  <%= button_tag(type: "submit", name: "") do%>
    <i class="fa-solid fa-magnifying-glass"></i>
  <% end %>
<% end %>

app/views/pages/_search_bar.html.erb
<div class="search-bar-items">
      <%= simple_form_for :search, url: items_path, method: :get, html: { class: "d-flex" }, data: { controller: "reset-search"} do |f| %>
        <%= f.input :query,
          input_html: {
              class: "search-model",
              placeholder: "Quoi ?",
              data: {
                reset_search_target: "search"
              }
          }, label: false %>
        <%= f.input :address,
          input_html: {data: {address_autocomplete_target: "address"}, class: "d-none"},
          wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}},
          label: false
        %>
        <%= button_tag type: 'submit' do %>
          <i class="fa-solid fa-magnifying-glass"></i>
        <% end %>
      <% end %>
</div>

app/views/pages/index.html.erb
<div class="container-page-index">
  <header class="header-pages">
    <div class="top-bar">
      <% if !@user.nil? %>
        <% if @user.companies.count > 0 %>
          <div class="left-link">
            <%= link_to dashboard_path, class: 'pro-space-link' do %>
              <span class="pro-space"><p>Espace Pro</p></span>
            <% end %>

          </div>
        <% else %>
          <div class="left-link">
            <span class="pro-space"><p>Espace Pro</p></span>
          </div>
        <% end %>
        <div class="right-link">
          <%= link_to destroy_user_session_path, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: 'logout-link' do %>
            <i class="fa-solid fa-arrow-right-from-bracket logout-link" style="color: #000000;"></i>
          <% end %>
        </div>
      <% else %>
        <div class="left-link">
          <span class="pro-space"><p>Espace Pro</p></span>
        </div>
      <% end %>
    </div>
    <div class="logo-container">
      <div class="logo">
        <%= image_tag "logo.png" %>
      </div>
    </div>
    <div class="search-bar mt-100">
      <%= simple_form_for :search, url: items_path, method: :get, html: { class: "d-flex" }, data: { controller: "reset-search" } do |f| %>
        <%= f.input :query,
          input_html: {
              class: "search-model",
              placeholder: "Quoi ?",
              data: {
                reset_search_target: "search"
              }
          }, label: false %>
        <%= f.input :address,
          input_html: {data: {address_autocomplete_target: "address", reset_search_target:'address'}, class: "d-none"},
          wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}},
          label: false
        %>
        <%= button_tag type: 'submit', input_html: { data: { action: "input->reset-search#clearSearch"} } do %>
          <i class="fa-solid fa-magnifying-glass"></i>
        <% end %>
      <% end %>
    </div>
    <h2 class="tagline">Des <span>sneakers</span> locales, un impact global</h2>
    <div class="swiper" data-controller="swiper">
      <div class="swiper-wrapper">
          <div class="swiper-slide"><img src="https://images.pexels.com/photos/786003/pexels-photo-786003.jpeg?auto=compress&cs=tinysrgb&w=800" alt="Les nouveautés"></div>
          <div class="swiper-slide"><img src="https://images.pexels.com/photos/1025996/pexels-photo-1025996.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2" alt="La Rentrée"></div>
          <div class="swiper-slide"><img src="https://images.unsplash.com/photo-1599654766593-d43341df51cb?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fHNuZWFrZXIlMjBjaGlsZHJlbnxlbnwwfDB8MHx8fDA%3D" alt="Child"></div>
          <div class="swiper-slide"><img src="https://images.pexels.com/photos/9015359/pexels-photo-9015359.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2" alt="Child"></div>
        </div>
        <div class="swiper-pagination"></div>
      <div class="swiper-scrollbar"></div>
    </div>
  </header>

  <main data-controller="tabs">
    <div class="category-tabs">
      <button class="tab-page-index active" data-target="homme" data-tabs-target="tab" data-action="click->tabs#switchTab">Homme</button>
      <button class="tab-page-index" data-target="femme" data-tabs-target="tab" data-action="click->tabs#switchTab">Femme</button>
      <button class="tab-page-index" data-target="enfant" data-tabs-target="tab" data-action="click->tabs#switchTab">Enfant</button>
    </div>

    <div id="homme" class="card-section-page-index active" data-tabs-target="section">
      <div class="card-page-index">
        <img src="https://img.freepik.com/free-photo/white-sneakers-closeup-men-s-apparel-summer-fashion-beach-photoshoot_53876-101216.jpg?ga=GA1.1.1043838493.1723553977&semt=ais_hybrid" alt="Les nouveautés">
        <p>Tout pour la rentrée</p>
      </div>
      <div class="card-page-index">
        <img src="https://img.freepik.com/free-photo/man-runner-tying-lace-shoes-sport-training-road_23-2148123967.jpg?ga=GA1.1.1043838493.1723553977&semt=ais_hybrid" alt="Modèles inspirants">
        <p>Tout pour le sport</p>
      </div>
      <div class="card-page-index">
        <img src="/assets/tendance.png" alt="iconic">
        <p>Nos modèles iconiques</p>
      </div>
      <div class="card-page-index">
        <img src="/assets/editions.png" alt="tendances">
        <p>Éditions limitées</p>
      </div>
    </div>

    <div id="femme" class="card-section-page-index" data-tabs-target="section">
      <div class="card-page-index">
        <img src="https://images.unsplash.com/photo-1699594165148-0eb85ec79666?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTh8fGZhc2hpb24lMjBzbmVha2Vyc3xlbnwwfDB8MHx8fDA%3D" alt="La Rentrée">
        <p>Les nouveautés tendances</p>
      </div>
      <div class="card-page-index">
        <img src="https://images.unsplash.com/photo-1539185441755-769473a23570?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MzJ8fGZhc2hpb24lMjBzbmVha2Vyc3xlbnwwfDB8MHx8fDA%3D" alt="La tendence de ce été">
        <p>Sport & style</p>
      </div>
      <div class="card-page-index">
        <img src="https://img.freepik.com/free-photo/white-sneakers-closeup-men-s-apparel-summer-fashion-beach-photoshoot_53876-101216.jpg?ga=GA1.1.1043838493.1723553977&semt=ais_hybrid" alt="Les nouveautés">
        <p>Tout pour la rentrée</p>
      </div>
      <div class="card-page-index">
        <img src="https://img.freepik.com/free-photo/man-runner-tying-lace-shoes-sport-training-road_23-2148123967.jpg?ga=GA1.1.1043838493.1723553977&semt=ais_hybrid" alt="Modèles inspirants">
        <p>Tout pour le sport</p>
      </div>
    </div>

    <div id="enfant" class="card-section-page-index" data-tabs-target="section">
      <div class="card-page-index">
        <img src="https://images.unsplash.com/photo-1599654766593-d43341df51cb?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fHNuZWFrZXIlMjBjaGlsZHJlbnxlbnwwfDB8MHx8fDA%3D" alt="Child">
        <p>Retour à l'école</p>
      </div>
      <div class="card-page-index">
        <img src="https://images.unsplash.com/photo-1659614404055-670edff49a1b?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8c25lYWtlciUyMHlvdW5nJTIwYWR1bHR8ZW58MHwwfDB8fHww" alt="young adults">
        <p>Mini-tendances</p>
      </div>
      <div class="card-page-index">
        <img src="https://images.unsplash.com/photo-1699594165148-0eb85ec79666?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTh8fGZhc2hpb24lMjBzbmVha2Vyc3xlbnwwfDB8MHx8fDA%3D" alt="La Rentrée">
        <p>Les nouveautés tendances</p>
      </div>
      <div class="card-page-index">
        <img src="https://images.unsplash.com/photo-1539185441755-769473a23570?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MzJ8fGZhc2hpb24lMjBzbmVha2Vyc3xlbnwwfDB8MHx8fDA%3D" alt="La tendence de ce été">
        <p>Sport & style</p>
      </div>
    </div>
    <% unless current_user.nil? %>
      <%= render "shared/button_cart" %>
    <% end %>
  </main>
  <%= render 'footer' %>
</div>